#!/usr/bin/env bash

# Automation Script from coc.nvim: https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim

set -o nounset    # error when referencing undefined variable
set -o errexit    # exit when command fails

# install coc for neovim
mkdir -p ~/.local/share/nvim/site/pack/coc/start
cd ~/.local/share/nvim/site/pack/coc/start
curl --fail -L https://github.com/neoclide/coc.nvim/archive/release.tar.gz | tar xzfv -

# Install extensions
mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions
if [ ! -f package.json ]
then
  echo '{"dependencies":{}}'> package.json
fi

# Change extension names to the extensions you need
npm install coc-explorer coc-css coc-tsserver coc-json coc-html --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod

